# Generated by Django 3.1.5 on 2021-01-29 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0003_auto_20210129_1300"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
