# Generated by Django 3.1.5 on 2021-01-29 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0004_auto_20210129_1301"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="products",
        ),
    ]
