# Generated by Django 3.1.5 on 2021-01-26 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='price',
            field=models.DecimalField(decimal_places=2, default=5.99, max_digits=5),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='added',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='description',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
