# Generated by Django 3.1.5 on 2021-01-26 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0002_remove_ingredient_pizzas'),
        ('pizzas', '0002_auto_20210126_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='description',
        ),
        migrations.AddField(
            model_name='pizza',
            name='ingredients',
            field=models.ManyToManyField(to='ingredients.Ingredient'),
        ),
    ]
