# Generated by Django 3.1.5 on 2021-01-26 22:26

from django.db import migrations, models
import pizza_online.apps.pizzas.models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0003_auto_20210126_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=pizza_online.apps.pizzas.models.upload_image_path),
        ),
    ]
