# Generated by Django 3.1.5 on 2021-01-26 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pizzas', '0002_auto_20210126_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pizzas', models.ManyToManyField(to='pizzas.Pizza')),
            ],
        ),
    ]
