# Generated by Django 3.1.5 on 2021-01-26 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='pizzas',
        ),
    ]
