# Generated by Django 3.1.5 on 2021-01-30 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_product_extra_ingredients"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="extra_ingredients",
        ),
    ]
